workspace 'PartyUP.xcworkspace'
use_frameworks!

target 'PartyUP' do
	project 'PartyUP.xcodeproj'
	platform :ios, '8.0'
	pod 'AWSS3'
	pod 'AWSDynamoDB'
	pod 'AWSCognito'
	pod 'DACircularProgress'
	pod 'Alamofire'
	pod 'SwiftyJSON'
	pod 'INTULocationManager'
	pod 'PBJVision'
	pod 'VIMVideoPlayer'
	pod 'ActionSheetPicker-3.0'
	pod 'SCLAlertView'
	pod 'Flurry-iOS-SDK'
	pod 'MarqueeLabel'
	pod 'Instructions'
	pod 'FBSDKLoginKit'
	pod 'KeychainAccess', '~> 2.4'
	pod 'LocationPickerViewController'
	pod 'SwiftDate', :git => 'https://github.com/malcommac/SwiftDate.git', :branch => 'feature/swift_23'
end
