workspace 'PartyUP.xcworkspace'
use_frameworks!

target 'PartyUP' do
	project 'PartyUP.xcodeproj'
	platform :ios, '8.0'
	pod 'AWSS3'
	pod 'AWSDynamoDB'
	pod 'AWSCognito'
	pod 'DACircularProgress'
	pod 'Alamofire'
	pod 'SwiftyJSON'
	pod 'INTULocationManager'
	pod 'LMGeocoder'
	pod 'PBJVision'
	pod 'VIMVideoPlayer'
	pod 'ActionSheetPicker-3.0'
	pod 'SCLAlertView'
	pod 'Flurry-iOS-SDK'
	pod 'MarqueeLabel'
	pod 'Instructions'
	pod 'FBSDKLoginKit'
	pod 'KeychainAccess'
	pod 'LocationPickerViewController'
end
